apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
      evaluation_interval: 1m
      external_labels:
        job: '~".+"'
    scrape_configs:
    - job_name: 'prom-federate'
      honor_labels: true
      metrics_path: /federate
      honor_timestamps: true
      scheme: http
      params:
        'match[]':
          - '{app="ratings"}'

      static_configs:
      - targets:
        - 192.168.15.201:9090
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-prom-master
  namespace: prom-master
