apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: prom-master
  namespace: prom-master
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9090
  selector:
    app: prom-master
  type: LoadBalancer
status:
  loadBalancer: {}
